name: Build LaTeX document
on: [push]
jobs:
  build_LaTeX:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-actions@v3
        with:
          root_file: main.tex
      - name: Upload PDF File
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: ProblemDescription.pdf
